### ISSUE TITLE
Limit brightness of face light

### ISSUE THREAD

**Issue by daweizhangau** [dckiller51/esphome-yeelight-led-screen-light-bar#11]
Turning on both background light and face light at 100% the same time will cause voltage drop suddenly, causing the micro controller to restart. 

If the turning on behavior is always-turn-on, it would run into a dead loop, so OTA won't work, and have to rewire the firmware with wires. 

Brightness too high also causes overheating issue.

A simple solution is to limit the max_power of each output. Any value under 0.9 should be OK, but I use 0.85.  

```yaml
output:
  - platform: esp8266_pwm
    pin: GPIO12
    id: output_cw
    power_supply: power
    frequency: 64 Hz
    max_power: 0.85  # <- limit brightness to prevent voltage drop
  - platform: esp8266_pwm
    pin: GPIO5
    id: output_ww
    power_supply: power
    frequency: 64 Hz
    max_power: 0.85  # <- limit brightness to prevent voltage drop
```
